dist: bionic

language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

env:
  global:
    - DB_CONNECTION="mysql"
    - DB_TEST_HOST="127.0.0.1"
    - DB_TEST_DATABASE="testing"
    - DB_TEST_USERNAME="travis"
    - DB_TEST_PASSWORD=""

  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS="--prefer-stable"

before_script:
  - mysql -e 'create database testing;'
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget --output-document=/tmp/ocular.phar https://scrutinizer-ci.com/ocular.phar && php /tmp/ocular.phar code-coverage:upload --format=php-clover coverage.clover
